### ISSUE TITLE
义父感谢！！！

### ISSUE THREAD

**Issue by CheemsForChips** [deopllj/Youdao-mindmap-to-Xmind#1]
垃圾考研党 整理政治知识点 奈何有道云这个sb手机端的mindmap难用的一批 无奈转xmind 本想自己写一个 谁知有开源的 已成成功转换格式 感谢

**Comment by deopllj** [comment]
很高兴能帮到你！
这个项目本来只是我大学时期的一个习作，没想到现在这些代码还能使用。
祝成功上岸。
